project_name: gitops-ee
# release:
#   disable: true
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ONLY_BINARY*
builds:
  - <<: &build_defaults
      binary: 'gitops'
      main: ./cmd/gitops
      flags:
        - -trimpath
      ldflags:
        - -s -w
        - '{{ .Env.LDFLAGS }}'
      env:
        - CGO_ENABLED=0
    id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    goarm:
      - 7
  - <<: *build_defaults
    id: linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    goarm:
      - 7
  - <<: *build_defaults
    id: linux-arm
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
  - <<: *build_defaults
    id: darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
  - <<: *build_defaults
    id: darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
  - <<: *build_defaults
    id: windows-amd64
    goos:
      - windows
    goarch:
      - amd64
