policy-agent:
  enabled: true
  # maybe we disable the policy-agent with tilt so ignore timeouts etc
  failurePolicy: Ignore
  config:
    accountId: "weaveworks"
    clusterId: "tilt-cluster"

config:
  logLevel: debug
  git:
    type: github
    hostname: github.com
  capi:
    templates:
      namespace: default
      injectPruneAnnotation: enabled
      addBasesKustomization: enabled
    clusters:
      namespace: ""
    repositoryURL: ""
    repositoryApiURL: ""
    repositoryPath: "./management-clusters/{{ .MANAGEMENT_CLUSTER }}/organizations/{{ .organization }}/workload-clusters"
    repositoryClustersPath: "./mapi"
    baseBranch: main
    extraReplacementFields:
      organization: namespace:{{ .NAMESPACE }}:labels:giantswarm.io/organization

  ui:
    footer:
      hideVersion: false
      content: "&nbsp;"

tls:
  enabled: false

# Turns on pipelines features when using Tilt.
enablePipelines: true

# Turns on explorer globally. See the explorer.enabledFor option to enable it for specific components.
explorer:
  enabledFor:
    - applications
    - sources
    - gitopssets
    - templates
    - clusterdiscovery

# Turns on terraform UI features for local dev
enableTerraformUI: true

envVars:
  - name: WEAVE_GITOPS_FEATURE_TENANCY
    value: "true"
  - name: WEAVE_GITOPS_FEATURE_CLUSTER
    value: "true"
  - name: WEAVE_GITOPS_USERS_CLIENTS_TTL
    value: "30s"
  - name: WEAVE_GITOPS_FEATURE_GITOPS_RUNTIME
    value: "true"
  - name: WEAVE_GITOPS_FEATURE_TELEMETRY
    value: "true"


extraEnvVarsSecret: ""

# Turns on UI elements for GitOps Run
enableRunUI: true

gitopssets-controller:
  enabled: true

cluster-reflector-controller:
  enabled: true

# Re-clarify capiEnabled
global:
  capiEnabled: true

enableNewPipelines: true

# Enable ingress running under a path
# Note:
# Run INSTALL_NGINX_INGRESS=1 DELETE_GITOPS_DEV_REPO=1 ./tools/reboot.sh and tilt up
# Open http://localhost:30080/weave-gitops-enterprise # access the weave-gitops-enterprise app
ingress:
  enabled: true
  hosts:
    - host: ""
      paths:
        - path: /weave-gitops-enterprise
          pathType: Prefix
